Gym/Gym/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('msfitcaregym.urls')),
    re_path('^', include('django.contrib.auth.urls')),
]

Gym/msfitcaregym/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #import this


app_name = 'msfitcaregym'

urlpatterns = [
    path('home/',views.index,name='home'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('login/',views.Login,name='login'),
    path('logout/',views.Logout,name='logout'),
    path('hours/',views.WorkingHours,name='hours'),
    path('savehours/',views.saveHours,name='savehours'),
    path('pricing/',views.Pricing,name='pricing'),
    path ('removepricing/<int:pk>/', views.remove_pricing, name = 'removepricing'),
    path('removepricingphysio/<int:pk>/', views.remove_pricing_physio, name='removepricingphysio'),
    path('register/',views.Register, name='register'),
    path('registrationform/',views.RegistrationForm,name='registrationform'),
    path('userprogram/',views.UserProgram,name='userprogram'),
    path('programperday/',views.UserProgramPerDay,name='programperday'),
    path('displayuserprogram/',views.displayUserProgram, name='displayuserprogram'),
    path('displayprogramhistory/',views.displayProgramHistory,name='displayprogramhistory'),
    path('editprogramuser/',views.EditUserProgram,name='editprogramuser'),
    path('userprogramhistory/',views.UserProgramHistory,name='userprogramhistory'),
    path('userprogramperdayedit/<int:pk>/',views.UserProgramPerDayEdit1,name='programperdayedit1'),
    # path('programperdayedit/',views.UserProgramPerDayEdit, name='programperdayedit'),
    path('editday/<int:pk>/',views.EditDay,name='editday'),
    path('displayDay/<int:pk>/',views.displayDay,name='displayday'),
    path('addextraday/',views.addExtraDay,name='addextraday'),
    path('addpayment/',views.Payments,name='addpayments'),
    path('allpayments/',views.allPayments,name='allpayments'),
    path('editpayment/<int:pk>/',views.editPayments,name='editpayment'),
    path('userpayments/<int:pk>/',views.userPayments,name='userpayments'),
    path('paymentsuser/',views.paymentsUser,name='paymentsuser'),
    path('blockuser/<int:pk>/<str:acc>', views.BlockUser, name='blockuser'),
    path('checkann/',views.checkAnnouncements,name='checkannouncement'),
    path('savemodal/',views.saveModal,name='savemodal'),
    path('savemodaltest/', views.saveModaltest, name='savemodaltest'),
    path('removebodyparts/',views.removeBodyPart,name='removebodypart'),

    path('addcommentscard/',views.addCommentsCard,name='addcommentscard'),
    path('humanbody1/<int:pk>/',views.HumanBody1,name='humanbody1'),

    path('profile/',views.Profile,name='profile'),
    # path('humanbody/<int:pk>/',views.HumanBody,name='humanbody'),
    # path('displayhumanbody/<int:pk>/',views.DisplayHumanBody,name='displayhumanbody'),
    path('displayhumanbody1/<int:pk>/', views.DisplayHumanBody1, name='displayhumanbody1'),
    path('allexercises/',views.allExercises,name='allexercises'),
    path ('removeexercise/<int:pk>/', views.remove_exercise, name = 'removeexercise'),

    path('aboutus/',views.AboutUs, name='aboutus'),
    path('removeaboutus/<int:pk>/', views.remove_aboutus,name='removeaboutus'),
    path('removeprogram/<int:pk>/',views.remove_program,name='removeprogram'),
    path('removeprogramday/<int:pk>/',views.remove_program_day,name='removeprogramday'),
    path('announcements/',views.Announcements, name='announcements'),
    path('removeannouncement/<int:pk>/',views.remove_announcement,name = 'removeannouncement'),
    path('usersInfo/',views.UsersInfo,name='usersinfo'),
    path('blockuserInfo/<int:pk>/<str:acc>/',views.BlockUserInfo,name='usersinfoblock'),
    path('users/requests/<int:pk>/<str:acc>/', views.userRequestApprovalChange, name='usersRequestApprovalChange'),
    path('galery/',views.Galery,name='galery'),
    path('removegallery/<int:pk>/', views.remove_gallery, name='removegallery'),
    path('password/', views.change_password, name='change_password'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),


    path('physio/slots/',views.physioSlotsJSON, name='physioSlots'),
    path('physio/slots/add/',views.addPhysioSlot, name='physioSlotsAdd'),
    path('physio/admin/',views.adminPhysioCalendar, name='adminPhysioCalendar'),
    path('calendar/addSlots/',views.addSlotsCalendar, name='addSlotsCalendar'),
    path('slots/add/',views.addSlots, name='addSlots'),
    path('gym/slots/',views.gymSlotsJSON, name='gymSlots'),
    path('calendar/user/<int:pk>/',views.userGymCalendar, name='userGymCalendar'),
    path('calendar/admin/<int:pk>/',views.adminGymCalendar, name='adminGymCalendar'),
    path('calendar/admin/slot/users',views.gymAdminReservations, name='gymAdminReservations'),
    path('calendar/user/addReservation/', views.gymUserAddReservation, name='gymUserAddReservation'),
    path('calendar/user/removeReservation/', views.gymUserRemoveReservation, name='gymUserRemoveReservation'),
    path('calendar/admin/removeReservation/', views.gymAdminRemoveReservation, name='gymAdminRemoveReservation'),
    path('calendar/admin/addReservation/', views.gymAdminAddReservation, name='gymAdminAddReservation'),
    path('physio/slot/update/', views.physioSlotUpdate, name='physioSlotUpdate'),
    path('physio/slot/delete/', views.physioSlotDelete, name='physioSlotDelete'),
    path('physio/user/delete/', views.physioAdminRemoveReservation, name='physioUserDelete'),
    path('physio/user/removeReservation/', views.physioUserRemoveReservation, name='physioUserRemoveReservation'),
    path('physio/admin/addUser/', views.physioAdminAddReservation, name='physioAdminUserAdd'),
    path('physio/user/addReservation/', views.physioUserAddReservation, name='physioUserAdd'),
    path('physio/user/',views.userPhysioCalendar, name='userPhysioCalendar'),
    path('daysClosed/',views.daysClosed, name='daysClosed'),
    path('addDayClosed/',views.addDayClosed, name='addDayClosed'),
    path('removeDayClosed/<int:repeating>/<int:pk>',views.removeDayClosed, name='removeDayClosed'),
    path('newCard/',views.physioNewCard, name='physioNewCard'),
    path('userCards/<int:pk>/',views.userCards, name='userCards'),

    path('adminRegistrationForm/',views.adminRegistrationForm,name='adminRegistrationForm'),
    path('displayForm/<int:pk>/',views.displayRegistrationForm,name='displayform'),

    path('adminReservations/<int:pk>/',views.adminReservations, name='adminReservations'),
    path('showReservations/',views.showReservations, name='showReservations'),
    path('userReservations/',views.userReservations, name='userReservations'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gym/msfitcaregym/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import CASCADE
import datetime


# Create your models here.
class HomePageText(models.Model):
    text = models.TextField(max_length=6000, null= True, blank=True)
    def __str__(self):
        return '{}'.format(self.text)

class WorkingHours(models.Model):
    id_day = models.AutoField(primary_key = True)
    day = models.CharField(max_length=100, null=True, blank=True)
    time = models.CharField(max_length=200, null=True, blank=True)

class Packages(models.Model):
    id_package = models.AutoField(primary_key = True)
    price = models.PositiveIntegerField(null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=500, null=True,blank=True)
    special_offer = models.BooleanField(null=True, blank=True, default = False)
    def __str__(self):
        return '{} : {}'.format(self.duration, self.price)

class PhysioPrices(models.Model):
    id_package = models.AutoField(primary_key = True)
    price = models.PositiveIntegerField(null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=500, null=True,blank=True)
    def __str__(self):
        return '{} : {}'.format(self.duration, self.price)

class UserProfile(models.Model):
    goals = {
        ('Υγεία','Υγεία'),
        ('Μείωση Βάρους', 'Μύωση Βάρους'),
        ('Αύξηση Βάρους','Αύξηση Βάρους'),
        ('Αποκατάσταση Τραυματισμών','Αποκατάσταση Τραυματισμών'),
        ('Συντήρηση','Συντήρηση'),
    }
    status_selection = [
        ('Request', 'Request'),
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected'),
        ('Revoke', 'Revoke'),
        ('NoUser', 'NoUser'),
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=CASCADE,null=True, blank= True)
    birthday= models.DateField(null=True, blank= True)
    job = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length= 15, null=True, blank=True)
    Address = models.CharField(max_length=200, null=True,blank=True)
    height = models.PositiveIntegerField(null=True,blank=True)
    weight = models.FloatField(null=True, blank=True)
    goal = models.CharField(max_length=100, choices=goals, null=True,blank=True)
    first_time_gym = models.BooleanField(null=True, blank=True)
    smoking = models.BooleanField(null=True, blank=True)
    surgery = models.CharField(max_length=300, blank=True, null=True)
    heart_problems = models.CharField(max_length=300, blank=True, null=True)
    medicines = models.CharField(max_length=300, blank=True, null=True)
    normal_blood_test = models.BooleanField(blank=True, null=True)
    cardiac_test = models.BooleanField(blank=True,null=True)
    epilepsy = models.CharField(max_length=200, blank=True, null=True)
    headache = models.CharField(max_length=200, blank=True, null=True)
    myosceletical_problems = models.CharField(max_length=300, null=True, blank=True)
    other_problems = models.CharField(max_length=300, null=True,blank=True)
    stable_weight = models.BooleanField(null=True, blank=True)
    approve = models.BooleanField(null=True, blank=True)
    package_choice = models.ForeignKey('Packages', on_delete=CASCADE, null=True, blank=True)
    accountStatus = models.CharField(max_length=30, choices=status_selection, default="Request", null=False, blank=False)
    checkann = models.DateTimeField(null=True,blank=True)
    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

class Type(models.Model):
    id_type = models.AutoField(primary_key = True)
    Title = models.CharField(max_length=200, null=True,blank=True)
    total_persons = models.PositiveIntegerField(null=True,blank=True)
    active = models.BooleanField(null=True,blank=True)

class Slots(models.Model):
    id_slot = models.AutoField(primary_key = True)
    type = models.ForeignKey('Type', on_delete=CASCADE)
    day=models.IntegerField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    valid_from = models.DateField()
    valid_to = models.DateField(null=True,blank=True)

class GymReservations(models.Model):
    id_reservation = models.AutoField(primary_key = True)
    date = models.DateField()
    user = models.ForeignKey('UserProfile',on_delete=CASCADE)
    time = models.ForeignKey('Slots', on_delete=CASCADE)
    type = models.ForeignKey('Type', on_delete=CASCADE)
    attendance = models.BooleanField(default=True)

class daysClosed(models.Model):
    id_day = models.AutoField(primary_key=True)
    date = models.DateField()

class repeatingDaysClosed(models.Model):
    id_day = models.AutoField(primary_key=True)
    month=models.PositiveSmallIntegerField()
    day = models.PositiveSmallIntegerField()
    valid_from = models.DateField()
    valid_to = models.DateField(null=True,blank=True)

class PhysioReservations(models.Model):
    id_reservation = models.AutoField(primary_key = True)
    date = models.DateField()
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    user = models.ForeignKey('UserProfile',null=True, blank=True ,on_delete=CASCADE)
    cancel = models.BooleanField(default=False)

class PhysioCard(models.Model):
    id_card = models.AutoField(primary_key = True)
    title= models.CharField(max_length=200)
    user = models.ForeignKey('UserProfile',on_delete=CASCADE)
    comments = models.TextField(null=True, blank=True)

class BodyParts(models.Model):
    id_part = models.AutoField(primary_key = True)
    physio_card = models.ForeignKey('PhysioCard',on_delete=CASCADE)
    circle_id = models.CharField(max_length=500,null=True, blank=True)
    partid = models.CharField(max_length=500, null=True, blank=True)
    x = models.FloatField(blank=True,null=True)
    y = models.FloatField(blank=True,null = True)
    color = models.CharField(max_length=500, null=True,blank=True)
    details = models.TextField(null=True, blank=True)

class Payments(models.Model):
    id_payment = models.AutoField(primary_key = True)
    user = models.ForeignKey('UserProfile',on_delete=CASCADE)
    pay_from = models.DateField(null=True, blank=True)
    pay_until = models.DateField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    package = models.ForeignKey('Packages', on_delete=CASCADE)

class ProgramUser(models.Model):
    goals = {
        ('Υγεία', 'Υγεία'),
        ('Μύωση Βάρους', 'Μύωση Βάρους'),
        ('Αύξηση Βάρους', 'Αύξηση Βάρους'),
        ('Αποκατάσταση Τραυματισμών', 'Αποκατάσταση Τραυματισμών'),
        ('Συντήρηση', 'Συντήρηση'),
    }
    id_program = models.AutoField(primary_key = True)
    user = models.ForeignKey('UserProfile', on_delete=CASCADE)
    date = models.DateField(null=True, blank=True,default= datetime.date.today())
    goal = models.CharField(max_length=300,choices=goals)

class Categories(models.Model):
    id_category = models.AutoField(primary_key = True)
    name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return '{}'.format( self.name)

class Exercises(models.Model):
    id_exercise = models.AutoField(primary_key = True)
    name = models.CharField(max_length=300, null=True, blank=True)
    category = models.ForeignKey('Categories', on_delete=CASCADE)

    def __str__(self):
        return '{}'.format( self.name)

class ProgramDates(models.Model):
    days = {
        ('Μέρα 1','Μέρα 1'),
        ('Μέρα 2', 'Μέρα 2'),
        ('Μέρα 3', 'Μέρα 3'),
        ('Μέρα 4', 'Μέρα 4'),
        ('Μέρα 5', 'Μέρα 5'),
        ('Μέρα 6', 'Μέρα 6'),
        }
    id_program_date = models.AutoField(primary_key = True)
    title = models.CharField(max_length=200,choices=days,null=True, blank=True)
    program = models.ForeignKey('ProgramUser', on_delete=CASCADE)

class ExercisesPerDate(models.Model):
    id_exercises_date = models.AutoField(primary_key = True)
    id_program_Date = models.ForeignKey('ProgramDates',on_delete=CASCADE,null=True,blank=True)
    id_exercises = models.ForeignKey('Exercises', on_delete=CASCADE)
    sets = models.PositiveIntegerField(null=True, blank=True)
    times = models.PositiveIntegerField(null=True, blank=True)
    color = models.CharField(max_length = 100,null = True, blank = True,default = '#000000')
    negative = models.BooleanField(null = True, blank = True, default = False)

class Announcements(models.Model):
    id_announcement = models.AutoField(primary_key = True)
    title = models.CharField(max_length= 100, null=True, blank=True)
    details = models.TextField(max_length=10000, null=True,blank=True)
    submited_date = models.DateTimeField(default = datetime.datetime.now())

class AboutUs(models.Model):
    id_about = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 200, null = True, blank = True)
    details = models.TextField(max_length = 10000, null = True, blank = True)
    photo = models.ImageField(upload_to = 'about_us',blank = True,null = True)

class Gallery(models.Model):
    id_gallery = models.AutoField(primary_key = True)
    title = models.CharField(max_length=300, null=True, blank=True)
    details = models.TextField(max_length=10000, null=True, blank = True)
    photo = models.ImageField(upload_to='gallery', null=True, blank=True)
    reservation=models.ForeignKey("Type",on_delete=CASCADE,null=True,blank=True)

Gym/templates/msfitcaregym/adminRegistrationform.html
{% extends 'msfitcaregym/base.html' %}
{% load static%}
{% load crispy_forms_tags %}

{% block title %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Registration Form</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
<!--    <link rel="stylesheet" href="{% static 'fonts1/fontawesome-all.min.css' %}">-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

{% endblock %}

{% block bg %}
    style="background:linear-gradient(rgba(0, 0, 0, 1), rgba(0, 0, 0, 1));"
{% endblock %}

{% block body_block %}
<section class="page-section cta" style="background-color: rgba(0, 0, 0, 0.1);">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner text-center rounded">
                        <div class="text-center">
                             <h4 class="text-dark mb-4">ΣΤΟΙΧΕΙΑ ΚΑΙ ΔΕΛΤΙΟ ΦΥΣΙΚΗΣ ΚΑΤΑΣΤΑΣΗΣ ΠΕΛΑΤΩΝ</h4>
                            </div>
                        <form class="user" method="post" id="rform">
                            {%csrf_token%}
                            <div class="row">
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ registration_form.first_name|as_crispy_field }}
                              </div>
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ registration_form.last_name|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ registration_form.job|as_crispy_field }}
                              </div>
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ registration_form.Address|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.birthday|as_crispy_field }}
                              </div>
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.height|as_crispy_field }}
                              </div>
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.weight|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ registration_form.phone|as_crispy_field }}
                              </div>
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ registration_form.first_time_gym|as_crispy_field }}
                              </div>
                            </div>
                            <div class="text-left">
                                <h5 class="text-dark mb-4">ΙΣΤΟΡΙΚΟ ΥΓΕΙΑΣ</h5>
                            </div>
                            <div class="row">
                              <div class="col-sm-12 mb-3 mb-sm-0">
                                {{ registration_form.heart_problems|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.medicines|as_crispy_field }}
                              </div>
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.surgery|as_crispy_field }}
                              </div>
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.epilepsy|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.headache|as_crispy_field }}
                              </div>
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.myosceletical_problems|as_crispy_field }}
                              </div>
                              <div class="col-sm-4 mb-3 mb-sm-0">
                                {{ registration_form.other_problems|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-sm-3 mb-3 mb-sm-0">
                                {{ registration_form.smoking|as_crispy_field }}
                              </div>
                              <div class="col-sm-3 mb-3 mb-sm-0">
                                {{ registration_form.normal_blood_test|as_crispy_field }}
                              </div>
                              <div class="col-sm-3 mb-3 mb-sm-0">
                                {{ registration_form.stable_weight|as_crispy_field }}
                              </div>
                              <div class="col-sm-3 mb-3 mb-sm-0">
                                {{ registration_form.cardiac_test|as_crispy_field }}
                              </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 mb-3 mb-sm-0">
                                    <label for="createUser">Δημιουργία Λογαριασμού?</label>
                                    <input type="checkbox" id="createUser" name="createUser" onclick="showForm('userDiv','id_email')">
                              </div>
                            </div>
                            <div class="row" style="display: none" id="userDiv">
                              <div class="col-sm-12 mb-3 mb-sm-0">
                                  <div id="div_id_email" class="form-group">
                                      <label for="id_email" class="">Email*</label>
                                      <div class="">
                                          <input type="email" name="email" maxlength="300" class="textinput textInput form-control" id="id_email">
                                      </div>
                                  </div>
                              </div>
                            </div>
                            {% if messages %}
                                {% for message in messages %}
                                    <p class="{{ message.tags }}" style="color: red;">
                                    {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
                                    </p>
                                {% endfor %}
                            {% endif %}
                            <button class="btn btn-primary text-white btn-user" type="submit">Καταχώρηση</button>
                            <hr>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</section>


{% endblock %}
{% block footer %}
<script>
    $( document ).ready(function() {
    $("#id_height").attr("required", true);
    $("#id_weight").attr("required", true);
    $("#id_age").attr("required", true);
    $("#id_phone").attr("required", true);
    });
</script>

<script>
    function showForm(name,inpname) {
      var x = document.getElementById(name);
      var inp=document.getElementById(inpname)
      if (x.style.display === "none") {
        x.style.display = "block";
        inp.required=true;
      } else {
        x.style.display = "none";
        inp.required=false;
      }
    }
</script>
{% endblock %}

Gym/templates/msfitcaregym/register.html
{% extends 'msfitcaregym/base.html' %}
{% load static%}

{% block title %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Register - Brand</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
<!--    <link rel="stylesheet" href="{% static 'fonts1/fontawesome-all.min.css' %}">-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

{% endblock %}

{% block bg %}
    style="background:linear-gradient(rgba(0, 0, 0, 1), rgba(0, 0, 0, 1));"
{% endblock %}

{% block body_block %}
<section class="page-section cta" style="background-color: rgba(0, 0, 0, 0.1);">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner text-center rounded">
                        {%if registered%}
                            <h1>Ευχαριστούμε για την εγγραφή σας</h1>
                            <h1>Για την ενεργοποίηση του λογαριασμού σας θα σας σταλεί email</h1>
                        {%else%}
                        <form class="user" method="post">
                            {%csrf_token%}
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="text" id="exampleFirstName" placeholder="Όνομα" name="{{user_form.first_name.name}}" {%if user_creation_form.first_name.value %} value="{{user_creation_form.first_name.value}}" {% endif %} required>
                                {{user_form.first_name.errors}}
                                </div>
                                <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="exampleLastName" placeholder="Επίθετο" name="{{user_form.last_name.name}}" {%if user_creation_form.last_name.value %} value="{{user_creation_form.last_name.value}}" {% endif %} required>
                                {{user_form.last_name.errors}}
                                </div>
                            </div>
                            <div class="form-group row">
<!--                                <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email Address" name="{{user_form.email.name}}" {%if user_creation_form.email.value %} value="{{user_creation_form.email.value}}" {% endif %} >-->
<!--                                {{user_form.first_name.errors}}-->
<!--                                </div>-->
                                <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="username" placeholder="Email" name="{{user_form.username.name}}" {%if user_creation_form.username.value %} value="{{user_creation_form.username.value}}" {% endif %} >
                                {{user_form.username.errors}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="password" id="examplePasswordInput" placeholder="Κωδικός" name="{{user_form.password1.name}}">
                                {{user_form.password1.errors}}
                                </div>

                                <div class="col-sm-6"><input class="form-control form-control-user" type="password" id="exampleRepeatPasswordInput" placeholder="Επανάληψη Κωδικού" name="{{user_form.password2.name}}">
                                {{user_form.password2.errors}}
                                </div>
                            </div>
                            <button class="btn btn-primary text-white btn-user" type="submit">Δημιουργία Λογαριασμού</button>
                        </form>
                        <div class="text-center"><a class="small" href="{%url 'msfitcaregym:password_reset'%}">Ξεχάσατε τον κωδικό σας;</a></div>
                        <div class="text-center"><a class="small" href="{%url 'msfitcaregym:login'%}">Έχετε ήδη λογαριασμό; Είσοδος!</a></div>
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock %}